stages:
  - build
  - release

build:
  stage: build
  image: debian:latest
  script:
    - echo "Building stage"
    - echo "${CI_JOB_ID}" > CI_JOB_ID.txt
    - echo $CI_COMMIT_TAG > TAG_VERSION.txt
    - apt update && apt upgrade -y
    - apt install -y zip
    - zip -r resourcepack.zip icon.png LICENSE pack.mcmeta pack.png README.md assets
  artifacts:
    paths:
      - CI_JOB_ID.txt
      - TAG_VERSION.txt
      - ./resourcepack.zip
    expire_in: never
  rules:
    - if: $CI_COMMIT_TAG

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
    - TAG_VERSION=$(cat TAG_VERSION.txt)
    - CI_ID=$(cat CI_JOB_ID.txt)
    - echo "${CI_ID} ${TAG_VERSION}"
    - rm -f TAG_VERSION.txt CI_JOB_ID.txt
    - |
      release-cli create --name "v$TAG_VERSION" --tag-name $TAG_VERSION --ref $CI_COMMIT_SHA \
      --assets-link "{\"name\":\"Resourcepack\",\"url\":\"https://gitlab.com/cbertran/mapcraft-resourcepack/-/jobs/`echo "${CI_ID}"`/artifacts/raw/resourcepack.zip\"}" \
  rules:
    - if: $CI_COMMIT_TAG
