name: Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: debian-latest
    steps:
      - name: Build datapack
        uses: actions/checkout@v3
        run: |
          apt update
          apt install -y zip
          zip -r resourcepack.zip icon.png LICENSE pack.mcmeta pack.png README.md assets version
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
             resourcepack.zip
